include ${KITTY_OS}.conf
include current-theme.conf

font_family      Hack Nerd Font Mono
font_size 12.0

tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 1
tab_powerline_style slanted
tab_title_template "{index}: {title.split('/')[-1]}"

update_check_interval 0

shell_integration no-cursor no-title

allow_remote_control yes

map cmd+ctrl+l discard_event
map cmd+t new_tab_with_cwd

#map ctrl+shift+p launch --type=overlay --allow-remote-control ~/bin/kitty-tab-switcher/kitty-tab-switcher
map ctrl+shift+p launch --type=overlay --allow-remote-control ~/bin/kitty-tab-switcher/kitty-tab-switcher
map ctrl+shift+i kitten tab_switcher.py
