format = """
[░▒](#d65d0e)\
$os\
$hostname\
[](bg:#d79921 fg:#d65d0e)\
$directory\
[](bg:#689d6a fg:#d79921)\
$git_branch\
$git_status\
$git_state\
[](fg:#689d6a bg:#458588)\
$python\
$battery\
[](fg:#458588 bg:#3c3836)\
$time\
[ ](fg:#3c3836)\
\n$character"""

[os]
style = "bg:#d65d0e fg:#fbf1c7"
format = "[$symbol]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[hostname]
ssh_only = false
style = "bg:#d65d0e fg:#fbf1c7"
format = '[$ssh_symbol$hostname]($style)'

[directory]
style= "fg:#fbf1c7 bg:#d79921"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[\\$](#98971a)"
error_symbol = "[\\$](#cc241d)"
vimcmd_symbol = "[\\$](#458588)"
vimcmd_replace_one_symbol = "[\\$](bold #b16286)"
vimcmd_replace_symbol = "[\\$](bold #b16286)"
vimcmd_visual_symbol = "[\\$](bold #d79921)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#fbf1c7 bg:#689d6a"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#fbf1c7 bg:#689d6a"
format = '[($all_status$ahead_behind)]($style)'

[git_state]
style = "fg:#fbf1c7 bg:#689d6a"

[python]
style = "fg:#fbf1c7 bg:#458588"
symbol = "🐍"
# disable detection through files and thus only show symbol if venv is active
detect_extensions = []
detect_files = []
format = "[ $symbol($virtualenv)]($style)"

[[battery.display]]
style = "fg:#fbf1c7 bg:#458588"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#fbf1c7 bg:#3c3836"
format = '[ $time ]($style)'
